### ISSUE TITLE
jnius.JavaException error

### ISSUE THREAD

**Issue by tinix84** [MauererM/pygeckocircuits#1]
Hi im running in win10 
my configuration is 

Miniconda3
Win10
Jdk 11.0.8

but I receive the following error

_**PS D:\OneDrive\NTB\GeckoCIRCUITS\pygeckocircuits> python .\PyGeckoExample.py
arg -p
arg 43036
Starting GeckoCIRCUITS JVM with 512 MB memory
Warning: Nashorn engine is planned to be removed from a future JDK release
GeckoCIRCUITS should now be running outside of MATLAB at port 43036
You are now connected to the GeckoCIRCUITS instance at port 43036
D:\OneDrive\NTB\GeckoCIRCUITS\pygeckocircuits/example.ipes
Warning: File loaded, autobackup check disabled!
Traceback (most recent call last):
  File ".\PyGeckoExample.py", line 56, in <module>
    ginst.openFile(fname)
  File "jnius\jnius_export_class.pxi", line 769, in jnius.JavaMethod.__call__
  File "jnius\jnius_export_class.pxi", line 863, in jnius.JavaMethod.call_method
  File "jnius\jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: class javax.swing.text.AbstractDocument$DefaultDocumentEventUndoableWrapper cannot be cast to class javax.swing.text.AbstractDocument$DefaultDocumentEvent (javax.swing.text.AbstractDocument$DefaultDocumentEventUndoableWrapper and javax.swing.text.AbstractDocument$DefaultDocumentEvent are in module java.desktop of loader 'bootstrap')**_

any idea?
thanks
Riccardo

**Comment by tinix84** [comment]
solved installing jdk 14
